### ISSUE TITLE
Nice tutorial!

### ISSUE THREAD

**Issue by FGRibreau** [Altoros/redis-labs-use-cases#1]
Nice tutorial @josx !

This demo app will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [project here](http://redisweekly.com/archive/140.html) :)

**Comment by josx** [comment]
@FGRibreau  thanks a lot!
Still more work coming!

**Comment by FGRibreau** [comment]
Great news @josx, ping me on twitter (@fgribreau) when they are up! :)
